### ISSUE TITLE
pip install not working

### ISSUE THREAD

**Issue by AmanteguiCode** [david-cortes/isotree#4]
Hi David,
I'm trying to reinstall the isotree library in order to use the new python functions to export the serialized model.

When i execute 

`pip install isotree`

The following error appears: 

```bash
$ pip install isotree
Collecting isotree
  Using cached https://files.pythonhosted.org/packages/8c/f4/c69cdafdc278f2c387b409a4ebdc415d1acd15f6a0d9592b3551e1c2c714/isotree-0.1.15.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-jEjgh3/isotree/setup.py", line 81, in <module>
        include_dirs=[np.get_include(), ".", "./src", cycereal.get_cereal_include_dir()],
      File "/home/bruiz/.local/lib/python2.7/site-packages/cycereal/__init__.py", line 40, in get_cereal_include_dir
        raise ValueError("Could not find header files from 'cycereal' - please try reinstalling with 'pip install --force cycereal'")
    ValueError: Could not find header files from 'cycereal' - please try reinstalling with 'pip install --force cycereal
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-jEjgh3/isotree/`
```

Already tried reinstalling cycereal (0.1.3), installed the requirements.txt file in your git code and the same error appears. Any insights?

**Comment by david-cortes** [comment]
Do you get the same error if you try Python 3 with pip >= 20?

**Comment by AmanteguiCode** [comment]
For some reason i had version 9 of pip3. Thanks for pointing it out.
